// The ZIP's images are kept byte-for-byte in assets/models, in archive order.
// Its entries are color backgrounds, so the named models use the matching colors.
export const portfolioModels = [
  { id: 'black', name: 'Modelo Preto', description: 'Elegante, com contraste marcante.', image: new URL('../../assets/models/model-10.png', import.meta.url).href, available: true, ink: '#ffffff', muted: '#d2d2d2' },
  { id: 'white', name: 'Modelo Branco', description: 'Claro, versátil e minimalista.', image: new URL('../../assets/models/model-06.png', import.meta.url).href, available: true, ink: '#17191b', muted: '#51565b' },
  { id: 'blue', name: 'Modelo Azul', description: 'Expressivo e profissional.', image: new URL('../../assets/models/model-02.png', import.meta.url).href, available: true, ink: '#ffffff', muted: '#dce6ff' },
  { id: 'red', name: 'Modelo Vermelho', description: 'Uma presença visual intensa.', image: new URL('../../assets/models/model-01.png', import.meta.url).href, available: false, ink: '#ffffff', muted: '#ffe0dc' },
  { id: 'orange', name: 'Modelo Laranja', description: 'Cor e energia na medida certa.', image: new URL('../../assets/models/model-03.png', import.meta.url).href, available: false, ink: '#17191b', muted: '#342820' },
  { id: 'pink', name: 'Modelo Rosa', description: 'Uma identidade vibrante.', image: new URL('../../assets/models/model-04.png', import.meta.url).href, available: false, ink: '#ffffff', muted: '#ffe1eb' },
  { id: 'lime', name: 'Modelo Lima', description: 'Criativo e cheio de personalidade.', image: new URL('../../assets/models/model-05.png', import.meta.url).href, available: false, ink: '#17191b', muted: '#3d4500' },
  { id: 'yellow', name: 'Modelo Amarelo', description: 'Luminosa e acolhedora.', image: new URL('../../assets/models/model-07.png', import.meta.url).href, available: false, ink: '#17191b', muted: '#493c15' },
  { id: 'green', name: 'Modelo Verde', description: 'Natural e contemporâneo.', image: new URL('../../assets/models/model-08.png', import.meta.url).href, available: false, ink: '#10231a', muted: '#183f2c' },
  { id: 'purple', name: 'Modelo Roxo', description: 'Criativo com profundidade.', image: new URL('../../assets/models/model-09.png', import.meta.url).href, available: false, ink: '#ffffff', muted: '#e6d9ff' },
  { id: 'startbootstrap-agency-1.0.2', name: 'Agency Studio', category: 'Agência', description: 'Agência criativa com serviços, equipe e portfólio.', tags: ['agência', 'empresa'], author: 'Start Bootstrap', license: 'Apache-2.0', accent: '#e0a500', image: '/models/thumbnails/startbootstrap-agency-1.0.2.jpg', available: true },
  { id: 'startbootstrap-clean-blog-1.0.2', name: 'Clean Blog', category: 'Blog', description: 'Blog editorial com artigos e navegação simples.', tags: ['blog', 'editorial'], author: 'Start Bootstrap', license: 'Apache-2.0', accent: '#397c8d', image: '/models/thumbnails/startbootstrap-clean-blog-1.0.2.jpg', available: true },
  { id: 'startbootstrap-freelancer-1.0.2', name: 'Freelancer', category: 'Portfólio', description: 'Portfólio com projetos, apresentação e contato.', tags: ['freelancer', 'criativo'], author: 'Start Bootstrap', license: 'Apache-2.0', accent: '#18a689', image: '/models/thumbnails/startbootstrap-freelancer-1.0.2.jpg', available: true },
  { id: 'startbootstrap-grayscale-1.0.3', name: 'Grayscale', category: 'Landing page', description: 'Página de apresentação em tons escuros e fotografia.', tags: ['landing', 'fotografia'], author: 'Start Bootstrap', license: 'Apache-2.0', accent: '#34383d', image: '/models/thumbnails/startbootstrap-grayscale-1.0.3.jpg', available: true },
  { id: 'startbootstrap-sb-admin-1.0.2', name: 'SB Admin', category: 'Painel', description: 'Painel com cartões, gráficos e tabelas.', tags: ['dashboard', 'dados'], author: 'Start Bootstrap', license: 'Apache-2.0', accent: '#286090', image: '/models/thumbnails/startbootstrap-sb-admin-1.0.2.jpg', available: true },
  { id: 'startbootstrap-sb-admin-2-1.0.5', name: 'SB Admin 2', category: 'Painel', description: 'Painel expandido com métricas e componentes.', tags: ['dashboard', 'saas'], author: 'Start Bootstrap', license: 'Apache-2.0', accent: '#4472ad', image: '/models/thumbnails/startbootstrap-sb-admin-2-1.0.5.jpg', previewUrl: '/models/startbootstrap-sb-admin-2-1.0.5/pages/index.html', available: true },
  { id: 'startbootstrap-stylish-portfolio-1.0.2', name: 'Stylish Portfolio', category: 'Portfólio', description: 'Portfólio de página única com destaque visual.', tags: ['portfólio', 'landing'], author: 'Start Bootstrap', license: 'Apache-2.0', accent: '#237e96', image: '/models/thumbnails/startbootstrap-stylish-portfolio-1.0.2.jpg', available: true },
  { id: 'city-square-bootstrap-responsive-web-template', name: 'City Square', category: 'Empresa', description: 'Site corporativo com capa urbana e seções de serviços.', tags: ['empresa', 'serviços'], author: 'WebThemez', license: 'Atribuição requerida', accent: '#d94741', image: '/models/thumbnails/city-square-bootstrap-responsive-web-template.jpg', available: true },
  { id: 'green-corp-flat-free-responsive-mobile-website', name: 'Green Corp', category: 'Empresa', description: 'Apresentação empresarial com tom natural.', tags: ['empresa', 'sustentabilidade'], author: 'WebThemez', license: 'Atribuição requerida', accent: '#48875f', image: '/models/thumbnails/green-corp-flat-free-responsive-mobile-website.jpg', available: true },
  { id: 'free-portfolio-html5-responsive-website-sam', name: 'Sam Portfolio', category: 'Portfólio', description: 'Currículo e projetos em um site pessoal.', tags: ['currículo', 'pessoal'], author: 'WebThemez', license: 'Atribuição requerida', accent: '#4f7494', image: '/models/thumbnails/free-portfolio-html5-responsive-website-sam.jpg', available: true },
  { id: 'getdoctor-free-bootstrap-responsive-website-template', name: 'Get Doctor', category: 'Saúde', description: 'Página de clínica com serviços e equipe.', tags: ['clínica', 'saúde'], author: 'WebThemez', license: 'CC BY 3.0', accent: '#27a1a8', image: '/models/thumbnails/getdoctor-free-bootstrap-responsive-website-template.jpg', available: true },
  { id: 'traveller-bootstrap-responsive-web-template', name: 'Traveller', category: 'Viagem', description: 'Site de viagens com destinos e galeria.', tags: ['turismo', 'viagem'], author: 'WebThemez', license: 'Atribuição requerida', accent: '#ed7e32', image: '/models/thumbnails/traveller-bootstrap-responsive-web-template.jpg', available: true },
  { id: 'free-bootstrap-template-restaurant-website-treehut', name: 'TreeHut', category: 'Restaurante', description: 'Restaurante com cardápio, pratos e equipe.', tags: ['gastronomia', 'restaurante'], author: 'WebThemez', license: 'CC BY 3.0', accent: '#a66109', image: '/models/thumbnails/free-bootstrap-template-restaurant-website-treehut.jpg', available: true },
  { id: 'coffee-shop-free-html5-template', name: 'Coffee Shop', category: 'Cafeteria', description: 'Cafeteria com cardápio e identidade acolhedora.', tags: ['café', 'gastronomia'], author: 'WebThemez', license: 'MIT do repositório; manter crédito', accent: '#765039', image: '/models/thumbnails/coffee-shop-free-html5-template.jpg', available: true },
  { id: 'wow-portfolio-multi-purpose-html5-template', name: 'Wow Portfolio', category: 'Portfólio', description: 'Galeria e serviços para profissionais criativos.', tags: ['galeria', 'criativo'], author: 'WebThemez', license: 'CC BY 3.0', accent: '#de5451', image: '/models/thumbnails/wow-portfolio-multi-purpose-html5-template.jpg', available: true },
  { id: 'grand-free-bootstrap-responsive-website-template', name: 'Grand', category: 'Empresa', description: 'Site institucional com projetos e equipe.', tags: ['empresa', 'projetos'], author: 'WebThemez', license: 'CC BY 3.0', accent: '#3597b5', image: '/models/thumbnails/grand-free-bootstrap-responsive-website-template.jpg', available: true },
  { id: 'learn-educational-free-responsive-web-template', name: 'Learn', category: 'Educação', description: 'Escola com cursos, sobre e contato.', tags: ['escola', 'cursos'], author: 'WebThemez', license: 'CC BY 3.0', accent: '#4d84af', image: '/models/thumbnails/learn-educational-free-responsive-web-template.jpg', available: true },
  { id: 'skytouch-onepage-bootstrap-responsive-web-template', name: 'SkyTouch', category: 'Landing page', description: 'Página única para apresentar um negócio.', tags: ['landing', 'empresa'], author: 'WebThemez', license: 'Atribuição requerida', accent: '#4c95aa', image: '/models/thumbnails/skytouch-onepage-bootstrap-responsive-web-template.jpg', available: true },
  { id: 'me-resume-personal-portfolio-responsive-template', name: 'Me Resume', category: 'Currículo', description: 'Currículo e portfólio profissional responsivo.', tags: ['currículo', 'pessoal'], author: 'WebThemez', license: 'Atribuição requerida', accent: '#aa6c51', image: '/models/thumbnails/me-resume-personal-portfolio-responsive-template.jpg', available: true },
  { id: 'park-city-bootstrap-html-real-estate-responsive-template', name: 'Park City', category: 'Imobiliária', description: 'Imóveis, serviços e equipe em um site de negócios.', tags: ['imóveis', 'empresa'], author: 'WebThemez', license: 'CC BY 3.0', accent: '#5d8a83', image: '/models/thumbnails/park-city-bootstrap-html-real-estate-responsive-template.jpg', available: true },
]

export const getPortfolioModel = id => portfolioModels.find(model => model.id === id) || portfolioModels[1]
export const templateModels = portfolioModels.filter(model => model.image.startsWith('/models/thumbnails/'))
export const modelPreviewUrl = model => templateModels.includes(model) ? model.previewUrl || `/models/${model.id}/index.html` : ''
