import { folioDevLogo } from './brand.js'

export const escapeHtml = value => String(value ?? '').replace(/[&<>"']/g, char => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', '"':'&quot;', "'":'&#39;' })[char])
export const brandMarkup = () => `<span class="folio-brand"><img src="${folioDevLogo}" alt="FolioDev" width="1086" height="162"></span>`
export const statusBadge = status => `<span class="status ${escapeHtml(status)}">${({ published:'Publicado', progress:'Em desenvolvimento', draft:'Rascunho' })[status] || 'Rascunho'}</span>`
export function projectCardMarkup(project, { actions = '', draggable = false } = {}) {
  return `<article class="card project-card explorer-project" ${draggable ? `draggable="true" data-drag-project="${escapeHtml(project.id)}" tabindex="0"` : ''} aria-label="Projeto ${escapeHtml(project.name)}"><${draggable?'button':'div'} class="project-cover" ${draggable ? `type="button" data-view-project="${escapeHtml(project.id)}" aria-label="Visualizar ${escapeHtml(project.name)}"` : ''}>${project.image ? `<img src="${escapeHtml(project.image)}" alt="Capa de ${escapeHtml(project.name)}" loading="lazy" width="480" height="270" draggable="false">` : `<span class="project-cover-fallback"><span class="mono">${escapeHtml(project.github || 'projeto')}</span><strong>${escapeHtml(project.name)}</strong></span>`}</${draggable?'button':'div'}><div class="project-card-body"><div class="project-card-title"><h2>${escapeHtml(project.name)}</h2>${statusBadge(project.status)}</div><p>${escapeHtml(project.description || 'Adicione o contexto deste projeto.')}</p><div class="tag-row">${String(project.tech || '').split(',').filter(x=>x.trim()).slice(0,4).map(x=>`<span class="tag mono">${escapeHtml(x.trim())}</span>`).join('')}</div>${actions ? `<div class="project-actions">${actions}</div>` : ''}</div></article>`
}
export function documentPreview({ profile, projects = [], compact = false }) {
  return `<div class="document-frame ${compact ? 'document-compact' : ''}"><div class="document-toolbar mono">foliodev.app/${escapeHtml(profile.username || 'seu-nome')}</div><div class="document-content"><div class="document-person"><span class="avatar">${profile.avatar ? `<img src="${escapeHtml(profile.avatar)}" alt="Foto de ${escapeHtml(profile.name)}" loading="lazy" width="64" height="64">` : escapeHtml((profile.name || 'Você').slice(0,2).toUpperCase())}</span><h3>${escapeHtml(profile.name || 'Seu nome')}</h3><p>${escapeHtml(profile.role || 'Desenvolvimento de software')}</p>${profile.bio ? `<p>${escapeHtml(profile.bio)}</p>` : ''}</div><div class="document-projects">${projects.slice(0,compact?2:4).map(project=>`<div class="document-project"><span class="mono">${escapeHtml(project.tech || 'projeto')}</span><h4>${escapeHtml(project.name)}</h4><p>${escapeHtml(project.description || '')}</p></div>`).join('')}</div></div></div>`
}
export const emptyMarkup = (title, description, action = '') => `<div class="empty-state-content"><span class="empty-monogram" aria-hidden="true">[ ]</span><h3>${escapeHtml(title)}</h3><p>${escapeHtml(description)}</p>${action}</div>`
export const skeletonMarkup = () => '<div class="skeleton-layout" aria-hidden="true"><div class="skeleton skeleton-title"></div><div class="skeleton"></div><div class="skeleton"></div><div class="skeleton"></div></div>'
