create table if not exists public.portfolio_leads (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null check (char_length(name) between 2 and 100),
  email text not null check (char_length(email) between 3 and 254),
  phone text not null default '' check (char_length(phone) <= 40),
  message text not null default '' check (char_length(message) <= 2000),
  potential text not null default 'Médio' check (potential in ('Alto', 'Médio', 'Baixo')),
  status text not null default 'Novo' check (status in ('Novo', 'Em contato', 'Concluído')),
  created_at timestamptz not null default now()
);

create index if not exists portfolio_leads_user_created_idx on public.portfolio_leads(user_id, created_at desc);
alter table public.portfolio_leads enable row level security;
revoke all on table public.portfolio_leads from anon, authenticated;
grant select, update, delete on table public.portfolio_leads to authenticated;
grant insert on table public.portfolio_leads to anon, authenticated;
grant usage, select on sequence public.portfolio_leads_id_seq to anon, authenticated;

create policy "portfolio_leads_owner_select" on public.portfolio_leads for select to authenticated
  using ((select auth.uid()) = user_id);
create policy "portfolio_leads_owner_update" on public.portfolio_leads for update to authenticated
  using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
create policy "portfolio_leads_owner_delete" on public.portfolio_leads for delete to authenticated
  using ((select auth.uid()) = user_id);
create policy "portfolio_leads_public_insert" on public.portfolio_leads for insert to anon, authenticated
  with check (exists (select 1 from public.profiles where profiles.user_id = portfolio_leads.user_id and profiles.published = true));
